[colors.primary]
background = "#191816"
foreground = "#dddddd"

[cursor]
style = "Beam"

[font]
size = 10.97

normal = { family = "JetBrainsMonoNL Nerd Font Mono", style = "Bold" }
italic = { family = "JetBrainsMonoNL Nerd Font Mono", style = "Italic" }
bold = { family = "JetBrainsMonoNL Nerd Font Mono", style = "ExtraBold" }

[scrolling]
history = 10000
multiplier = 3

[terminal.shell]
args = ["--login"]
program = "/bin/bash"

[window]
opacity = 1
decorations = "None"
dynamic_padding = true
